language: java
dist: xenial
jdk:
- openjdk8

env:
  KEYFILE=forever-project-b4434ecd4b50.json
  PROJECT_NAME=forever-project

script:
- mvn -q test -B
- mvn -q package

before_deploy:
- openssl aes-256-cbc -K $encrypted_35ead60980fb_key -iv $encrypted_35ead60980fb_iv -in forever-project-b4434ecd4b50.json.enc -out $KEYFILE -d
- gcloud auth activate-service-account --key-file $KEYFILE

deploy:
- provider: script
  script: mvn appengine:deploy -Dapp.deploy.projectId=$PROJECT_NAME &&
          gcloud app describe --project=$PROJECT_NAME
  skip_cleanup: true
  on:
    all_branches: true
